name: Topyak Bot 24-7

on:
  schedule:
    - cron: '0 */5 * * *' # Перезапуск каждые 5 часов
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pyTelegramBotAPI

      - name: Run bot
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: |
          python main.py
          
